version: '3'

services:
  frontend:
    build: 
      context: frontend/.
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${BACKEND_URL}
        NEXT_PUBLIC_BACKEND_API_KEY: ${API_KEY}
        NEXTAUTH_URL: ${BARMAN_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: on-failure
    ports:
      - "7000:3000"
    environment:
      NEXTAUTH_URL: ${BARMAN_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_BACKEND_API_URL: ${BACKEND_URL}
      NEXT_PUBLIC_BACKEND_API_KEY: ${API_KEY}
    env_file:
      - .env
  backend:
    build: be-barman/be-barman/.
    restart: on-failure
    ports:
      - "7001:5036"
    depends_on:
      - mariadb
    environment:
      DB_NAME: barman
      DB_SERVER: ${DB_SERVER}
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_VERSION_MAJOR: 10
      DB_VERSION_MINOR: 11
      DB_VERSION_BUILD: 3
      API_KEY: ${API_KEY}
  mariadb:
    image: mariadb:10.11.3
    restart: always
    ports:
      - "7003:3306"
    environment:
      MYSQL_DATABASE: barman
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: utf8mb4_unicode_ci
    volumes:
      - ./mariadb-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7002:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb